# Generated by Django 4.0 on 2022-04-22 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedInteractor',
            fields=[
                ('curated_interactor_id', models.AutoField(primary_key=True, serialize=False)),
                ('interactor_type', models.CharField(choices=[('protein', 'Protein'), ('gene', 'Gene'), ('mRNA', 'Mrna'), ('synthetic', 'Synthetic')], max_length=9)),
                ('curies', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('molecular_structure', models.CharField(blank=True, max_length=10000, null=True)),
                ('import_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'curated_interactor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EnsemblGene',
            fields=[
                ('ensembl_gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('ensembl_stable_id', models.CharField(blank=True, max_length=255, null=True)),
                ('import_time_stamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'ensembl_gene',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetaKey',
            fields=[
                ('meta_key_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'meta_key',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('ontology_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'ontology',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PredictionMethod',
            fields=[
                ('prediction_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parameters', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prediction_method',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SourceDb',
            fields=[
                ('source_db_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('external_db', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'source_db',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_id', models.AutoField(primary_key=True, serialize=False)),
                ('ensembl_division', models.CharField(max_length=255)),
                ('production_name', models.CharField(max_length=255)),
                ('taxon_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'species',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PredictedInteractor',
            fields=[
                ('predicted_interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('interactor_type', models.CharField(max_length=9)),
                ('curies', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('molecular_structure', models.CharField(blank=True, max_length=10000, null=True)),
                ('predicted_timestamp', models.DateTimeField()),
                ('curated_interactor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.curatedinteractor')),
                ('ensembl_gene', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.ensemblgene')),
                ('prediction_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.predictionmethod')),
            ],
            options={
                'db_table': 'predicted_interactor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OntologyTerm',
            fields=[
                ('ontology_term_id', models.AutoField(primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.ontology')),
            ],
            options={
                'db_table': 'ontology_term',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('doi', models.CharField(max_length=255)),
                ('import_timestamp', models.DateTimeField()),
                ('interactor_1', models.ForeignKey(db_column='interactor_1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='interaction_for_int1', to='home.curatedinteractor')),
                ('interactor_2', models.ForeignKey(db_column='interactor_2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='interaction_for_int2', to='home.curatedinteractor')),
                ('source_db', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.sourcedb')),
            ],
            options={
                'db_table': 'interaction',
                'managed': True,
                'unique_together': {('interactor_1', 'interactor_2', 'doi', 'source_db')},
            },
        ),
        migrations.AddField(
            model_name='ensemblgene',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.species'),
        ),
        migrations.AddField(
            model_name='curatedinteractor',
            name='ensembl_gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.ensemblgene'),
        ),
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('key_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.interaction')),
                ('meta_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.metakey')),
                ('ontology_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.ontologyterm')),
            ],
            options={
                'db_table': 'key_value_pair',
                'managed': True,
                'unique_together': {('interaction', 'meta_key', 'value')},
            },
        ),
    ]
